### PR TITLE
Use Kotlin 2.0.0, add wasmJs target

### PR DESCRIPTION
**Pull request by sayaka-sh**

### CODE REVIEW

**Comment by d1snin** [comment]
Hi! Thank you for your contribution! Have you tested your changes? Does it work properly?

**Comment by sayaka-sh** [comment]
Yes, I've tested this. You can see the succeeded build on Jitpack [here](https://jitpack.io/#toasterofbread/catppuccin-kotlin).

**Comment by d1snin** [comment]
Yeah, I see WASM binaries are built properly. Thank you again! We'll see how it's gonna be published on my repo.

**Comment by d1snin** [comment]
https://maven.d1s.dev/#/snapshots/com/catppuccin

WASM binaries are published successfully. Thank you again. I'll publish a release as soon as possible.

**Pull request merged**
